In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

dataset = pd.read_csv('new_car.csv', sep=',')
dataset.describe()

Unnamed: 0      car_ID   symboling   wheelbase   carlength    carwidth  \
count  151.000000  151.000000  151.000000  151.000000  151.000000  151.000000   
mean    80.331126   89.271523    1.079470   97.231788  171.249007   65.433113   
std     45.733536   52.538866    1.146142    4.989474   11.496648    1.883285   
min      0.000000    0.000000   -1.000000   86.600000  141.100000   60.300000   
25%     41.500000   43.500000    0.000000   94.500000  165.300000   63.850000   
50%     80.000000   88.000000    1.000000   96.300000  172.000000   65.400000   
75%    120.500000  136.500000    2.000000   99.100000  176.800000   66.500000   
max    158.000000  179.000000    3.000000  120.900000  208.100000   72.300000   

        carheight   curbweight  enginesize   boreratio      stroke  \
count  151.000000   151.000000  151.000000  151.000000  151.000000   
mean    53.096026  2456.960265  123.377483    3.293841    3.261126   
std      2.265329   496.254422   43.039012    0.267898    0.313987   
min     47.800000  1488.000000   61.000000    2.540000    2.070000   
25%     50.900000  2026.000000   94.500000    3.050000    3.110000   
50%     53.300000  2385.000000  110.000000    3.310000    3.270000   
75%     54.500000  2757.000000  136.000000    3.540000    3.410000   
max     59.100000  4066.000000  326.000000    3.940000    4.170000   

       compressionratio  horsepower      peakrpm     citympg  highwaympg  \
count        151.000000  151.000000   151.000000  151.000000  151.000000   
mean           9.037219  103.172185  5164.238411   25.403974   31.099338   
std            1.632963   40.180221   433.873157    6.561686    6.673085   
min            7.000000   48.000000  4200.000000   13.000000   16.000000   
25%            8.600000   70.000000  4800.000000   20.000000   26.000000   
50%            9.000000   92.000000  5200.000000   24.000000   31.000000   
75%            9.400000  116.000000  5500.000000   31.000000   37.000000   
max           21.900000  288.000000  6000.000000   49.000000   54.000000   

              price  
count    151.000000  
mean   12034.291238  
std     7245.170057  
min     5151.400000  
25%     7324.500000  
50%     9549.300000  
75%    14679.400000  
max    45400.700000

In [3]:
classes = [(0, 12000), 
           (12000, 46000)]

price = dataset[['price']]
categories = []

for _, x in price.iterrows():
    doneFlag = False
    for i, c in enumerate(classes):
        if c[0] <= x['price'] < c[1]:
            categories.append(i)
            doneFlag = True
            break

    if doneFlag:
        continue

dataset['Категория'] = categories
dataset['Категория'] = dataset['Категория'].replace({1: 'yes', 0: 'no'})
dataset.head(100)

Unnamed: 0  car_ID  symboling  wheelbase  carlength  carwidth  carheight  \
0            0       0          3       88.6      168.8      64.1       48.8   
1            1       1          3       88.6      168.8      64.1       48.8   
2            2       2          1       94.5      171.2      65.5       52.4   
3            3       3          2       99.8      176.6      66.2       54.3   
4            4       4          2       99.4      176.6      66.4       54.3   
..         ...     ...        ...        ...        ...       ...        ...   
95         101     115          0      107.9      186.7      68.4       56.7   
96         102     117          0      108.0      186.7      68.3       56.0   
97         103     118          1       93.7      157.3      63.8       50.8   
98         104     119          1       93.7      157.3      63.8       50.8   
99         105     120          1       93.7      157.3      63.8       50.6   

    curbweight  enginesize  boreratio  stroke  compressionratio  horsepower  \
0         2548         130       3.47    2.68               9.0         111   
1         2548         130       3.47    2.68               9.0         111   
2         2823         152       2.68    3.47               9.0         154   
3         2337         109       3.19    3.40              10.0         102   
4         2824         136       3.19    3.40               8.0         115   
..         ...         ...        ...     ...               ...         ...   
95        3075         120       3.46    3.19               8.4          97   
96        3130         134       3.61    3.21               7.0         142   
97        1918          90       2.97    3.23               9.4          68   
98        2128          98       3.03    3.39               7.6         102   
99        1967          90       2.97    3.23               9.4          68   

    peakrpm  citympg  highwaympg    price Категория  
0      5000       21          27  13495.6       yes  
1      5000       21          27  16500.1       yes  
2      5000       19          26  16500.7       yes  
3      5500       24          30  13950.2       yes  
4      5500       18          22  17450.8       yes  
..      ...      ...         ...      ...       ...  
95     5000       19          24  16630.7       yes  
96     5600       18          24  18150.7       yes  
97     5500       37          41   5572.8        no  
98     5500       24          30   7957.6        no  
99     5500       31          38   6229.3        no  

[100 rows x 18 columns]

In [4]:
dataset.head()

Unnamed: 0  car_ID  symboling  wheelbase  carlength  carwidth  carheight  \
0           0       0          3       88.6      168.8      64.1       48.8   
1           1       1          3       88.6      168.8      64.1       48.8   
2           2       2          1       94.5      171.2      65.5       52.4   
3           3       3          2       99.8      176.6      66.2       54.3   
4           4       4          2       99.4      176.6      66.4       54.3   

   curbweight  enginesize  boreratio  stroke  compressionratio  horsepower  \
0        2548         130       3.47    2.68               9.0         111   
1        2548         130       3.47    2.68               9.0         111   
2        2823         152       2.68    3.47               9.0         154   
3        2337         109       3.19    3.40              10.0         102   
4        2824         136       3.19    3.40               8.0         115   

   peakrpm  citympg  highwaympg    price Категория  
0     5000       21          27  13495.6       yes  
1     5000       21          27  16500.1       yes  
2     5000       19          26  16500.7       yes  
3     5500       24          30  13950.2       yes  
4     5500       18          22  17450.8       yes

In [5]:
# выберема категориальные переменные
from sklearn.compose import make_column_selector

categorical_selector = make_column_selector(dtype_include=[object])
categorical_columns = categorical_selector(dataset)
categorical_columns

['Категория']

In [6]:
# выберем численные показатели - это все показатели
categorical_selector = make_column_selector(dtype_include=[np.float_, np.int_, int, float])
numeric_columns = categorical_selector(dataset)
numeric_columns

['Unnamed: 0',
 'car_ID',
 'symboling',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginesize',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',
 'price']

In [7]:
df_cat = dataset[categorical_columns] #отберем только те столбцы в которых присутствует категориальная перемнная
df_cat.head()

Категория
0       yes
1       yes
2       yes
3       yes
4       yes

In [8]:
from sklearn.preprocessing import OrdinalEncoder

education_column = df_cat[["Категория"]]

print(df_cat['Категория'].unique()) #посмотрим какие виды образования присутствуют в выборке

encoder = OrdinalEncoder()   # вызываем кодировщик
encoder  = encoder.fit(df_cat[['Категория']])
df_cat['Категория'] = encoder.transform(df_cat[['Категория']])
df_cat

['yes' 'no']


C:\Users\gross\AppData\Local\Temp\ipykernel_2872\3490703640.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['Категория'] = encoder.transform(df_cat[['Категория']])


Категория
0          1.0
1          1.0
2          1.0
3          1.0
4          1.0
..         ...
146        1.0
147        1.0
148        0.0
149        0.0
150        0.0

[151 rows x 1 columns]

In [9]:
print(encoder.categories_)
print(len(encoder.categories_[0]))
print(df_cat['Категория'].unique())
df_cat['Категория'].unique().size

[array(['no', 'yes'], dtype=object)]
2
[1. 0.]


2

In [10]:
# OneHotEncoder

from sklearn.preprocessing import OneHotEncoder

#Создаем экземпляр OneHotEncoder с параметром sparse_output
encoder = OneHotEncoder(sparse_output=False)
# Установили кодировщик в столбец "Категория" в df_cat
encoder = encoder.fit(df_cat[['Категория']])
# Преобразовали столбец "Категория", используя выученную кодировку
education_encoded = encoder.transform(df_cat[['Категория']])
education_encoded

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.

In [11]:
feature_names = encoder.get_feature_names_out(input_features=["Категория"]) 
# получаем виды образования и на их основе создаем столбцы
education_encoded = pd.DataFrame(education_encoded, columns=feature_names)
education_encoded

Категория_0.0  Категория_1.0
0              0.0            1.0
1              0.0            1.0
2              0.0            1.0
3              0.0            1.0
4              0.0            1.0
..             ...            ...
146            0.0            1.0
147            0.0            1.0
148            1.0            0.0
149            1.0            0.0
150            1.0            0.0

[151 rows x 2 columns]

In [12]:
df_cat_new=df_cat.join(education_encoded)
df_cat_new=df_cat_new.drop(df_cat_new[['Категория']],axis=1)
df_cat_new

Категория_0.0  Категория_1.0
0              0.0            1.0
1              0.0            1.0
2              0.0            1.0
3              0.0            1.0
4              0.0            1.0
..             ...            ...
146            0.0            1.0
147            0.0            1.0
148            1.0            0.0
149            1.0            0.0
150            1.0            0.0

[151 rows x 2 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder
df_cat = dataset[categorical_columns] 
df_cat.head()

encoder = LabelEncoder()   # вызываем кодировщик
encoder  = encoder.fit(df_cat[['Категория']])
df_cat['Категория'] = encoder.transform(df_cat[['Категория']])
df_cat

C:\Users\gross\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\gross\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\Users\gross\AppData\Local\Temp\ipykernel_2872\795868433.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cat['Категория'] = encoder.transform(df_cat[['Категория']])


Категория
0            1
1            1
2            1
3            1
4            1
..         ...
146          1
147          1
148          0
149          0
150          0

[151 rows x 1 columns]

In [14]:
print(encoder.classes_)
print(len(encoder.classes_))
print(df_cat['Категория'].unique())
df_cat['Категория'].unique().size

['no' 'yes']
2
[1 0]


2

In [15]:
from sklearn.preprocessing import StandardScaler

X_train = np.array([[ 1., -1., 2.],
                     [ 2., 0., 0.],
                     [ 0., 1., -1.]])

scaler = StandardScaler()
scaler.fit(X_train)
print('Математическое ожидание')
print(scaler.mean_)
print('Дисперсия')
print(scaler.var_)
print('Преобразованный набор')
print(scaler.transform(X_train))

Математическое ожидание
[1.         0.         0.33333333]
Дисперсия
[0.66666667 0.66666667 1.55555556]
Преобразованный набор
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
